apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerservice
  labels:
    app: customerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerservice
  template:
    metadata:
      labels:
        app: customerservice
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: customerservice
          image: 467263215646.dkr.ecr.ap-northeast-1.amazonaws.com/skccuser16-customerservice:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/myReservations'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/myReservations'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
