apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerService
  labels:
    app: customerService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerService
  template:
    metadata:
      labels:
        app: customerService
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: customerService
          image: username/CustomerService:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/myReservations'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/myReservations'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5